sudo: required
language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang
script:
  - sudo apt-get update && sudo apt-get install valgrind
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./Pizzas-ut
  - valgrind ./Pizzas-ut
