name: Pizzas homework

on: [push, pull_request]

jobs:
  pizzas:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: install valgrind
      uses: sudo apt-get update && sudo apt-get install valgrind
    - name: mkdir build
      run: mkdir build
    - name: Compile
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: build
      run: |
        ./Pizzas-ut
        valgrind ./Pizzas-ut
